// PresetEngineTests.cpp - GREEN-phase tests for JSON engine presets
//
// Purpose: Verify that JSON preset deserialization produces correct engine
// simulations that can be loaded into a PistonEngineSimulator for audio
// production. Tests the full path: JSON -> PresetLoadResult -> Simulator.
//
// Architecture:
//   PresetEngineFactory::loadFromFile(path) returns PresetLoadResult
//   containing raw Engine*/Vehicle*/Transmission* pointers.
//   Caller creates a PistonEngineSimulator and calls loadSimulation().
//
// Test count: 15 (7 infrastructure + 4 per-engine * 2 engines)
//
// Data dependency: Tests need JSON preset files in test/fixtures/
// Generated by: engine-sim-preset-compiler <script.mr> <output.json>
//
// Build: cmake -DBUILD_PRESET_ENGINE_TESTS=ON
//   macOS: 15 tests (golden file tests use Piranha as reference)
//   iOS: 15 tests (golden file tests skipped -- no Piranha on iOS)

#include <gtest/gtest.h>
#include <memory>
#include <vector>
#include <cmath>
#include <cstring>
#include <chrono>
#include <thread>
#include <algorithm>
#include <fstream>

// Engine-sim headers
#include "simulator.h"
#include "piston_engine_simulator.h"
#include "engine.h"
#include "vehicle.h"
#include "transmission.h"
#include "synthesizer.h"
#include "starter_motor.h"

// Bridge headers
#include "simulator/PresetEngineFactory.h"
#include "simulator/SimulatorFactory.h"
#include "simulator/BridgeSimulator.h"
#include "simulator/SimulatorInitHelpers.h"
#include "simulator/EngineSimTypes.h"
#include "simulator/ScriptLoadHelpers.h"
#include "common/ILogging.h"
#include "TestPathHelpers.h"

// ============================================================================
// Constants
// ============================================================================

namespace {
    constexpr int TEST_SAMPLE_RATE = 48000;
    constexpr int STEREO_CHANNELS = 2;
    constexpr int IDLE_FRAMES = 4800;          // 100ms at 48kHz

    // Noise floor threshold for "non-silent" detection
    constexpr float NOISE_FLOOR = 100.0f;  // int16_t scale

    // Fixture paths - TEST_FIXTURE_DIR is set by CMake to the absolute
    // path of engine-sim-bridge/test/fixtures/
    const std::string FIXTURE_HONDA = TEST_FIXTURE_DIR "/01_honda_trx520.preset.json";
    const std::string FIXTURE_SUBARU = TEST_FIXTURE_DIR "/01_subaru_ej25_eh.preset.json";
}

// ============================================================================
// Test Harness - Preset simulator lifecycle and audio capture
//
// Creates a PistonEngineSimulator, loads a JSON preset via
// PresetEngineFactory::loadFromFile(), then calls loadSimulation().
// Uses PresetEngineFactory to load preset JSON and construct engine objects.
// ============================================================================

class PresetSimulatorHarness {
public:
    PresetSimulatorHarness()
        : simulator_(nullptr)
        , engine_(nullptr)
        , vehicle_(nullptr)
        , transmission_(nullptr)
    {}

    ~PresetSimulatorHarness() {
        cleanup();
    }

    // Load a JSON preset file and wire it into a PistonEngineSimulator.
    // Returns true on success.
    bool initialize(const std::string& fixturePath) {
        // Step 1: Load preset from JSON
        PresetLoadResult result = PresetEngineFactory::loadFromFile(fixturePath);
        if (!result.success()) {
            lastError_ = result.error;
            return false;
        }

        engine_ = result.engine;
        vehicle_ = result.vehicle;
        transmission_ = result.transmission;
        presetName_ = result.presetName;

        // Debug: Check intake BEFORE simulator load
        fprintf(stderr, "  [PRE-LOAD] intake pressure=%.2f atm\n",
            engine_->getIntake(0)->m_system.pressure() / 101325.0);


        // Step 2: Create and initialize PistonEngineSimulator
        auto* pistonSim = new PistonEngineSimulator();
        pistonSim->setFluidSimulationSteps(8);

        Simulator::Parameters params;
        params.systemType = Simulator::SystemType::NsvOptimized;
        pistonSim->initialize(params);
        // Use engine's requested simulation frequency (e.g. 40000 Hz for Honda)
        pistonSim->setSimulationFrequency(engine_->getSimulationFrequency());
        pistonSim->setTargetSynthesizerLatency(0.05);

        simulator_ = pistonSim;

        // Step 3: Load the engine into the simulator
        simulator_->loadSimulation(engine_, vehicle_, transmission_);

        // Debug: Check intake system state after loading
        fprintf(stderr, "  [INIT] After loadSimulation: intake pressure=%.2f atm\n",
            engine_->getIntake(0)->m_system.pressure() / 101325.0);

        // Step 4: Initialize convolution filters with unit impulses
        // Required because presets don't include WAV impulse response files
        // and ConvolutionFilter::f() would dereference null m_shiftRegister
        SimulatorInitHelpers::initializeConvolutionFilters(simulator_);

        return true;
    }

    // Run simulation and capture audio output (on-demand rendering)
    std::vector<int16_t> runAndCapture(int framesToGenerate) {
        if (!simulator_) return {};

        std::vector<int16_t> audioOutput(framesToGenerate * STEREO_CHANNELS, 0);

        const int framesPerStep = 100;
        int framesGenerated = 0;

        while (framesGenerated < framesToGenerate) {
            int framesToRead = std::min(framesPerStep, framesToGenerate - framesGenerated);

            simulator_->startFrame(1.0 / 60.0);
            while (simulator_->simulateStep()) {}
            simulator_->endFrame();
            simulator_->synthesizer().renderAudioOnDemand();

            int framesRead = simulator_->readAudioOutput(
                framesToRead,
                audioOutput.data() + framesGenerated * STEREO_CHANNELS
            );

            framesGenerated += framesRead;
            if (framesGenerated <= 100) {
                printf("    [CAPTURE] read %d frames (total %d/%d), rms so far=%.6f\n",
                    framesRead, framesGenerated, framesToGenerate, rms(audioOutput));
            }
        }

        return audioOutput;
    }

    // Calculate RMS of audio samples
    static float rms(const std::vector<int16_t>& samples) {
        if (samples.empty()) return 0.0f;
        double sumSquares = 0.0;
        for (int16_t s : samples) {
            double f = static_cast<double>(s) / 32768.0;
            sumSquares += f * f;
        }
        return static_cast<float>(std::sqrt(sumSquares / samples.size()));
    }

    // Check if audio contains signal above noise floor
    static bool hasSignal(const std::vector<int16_t>& samples, int16_t threshold = 100) {
        for (int16_t s : samples) {
            if (std::abs(s) > threshold) return true;
        }
        return false;
    }

    // Engine controls
    void setThrottle(float t) {
        if (simulator_ && simulator_->getEngine()) {
            // t=1.0 → WOT, t=0.0 → idle
            // DirectThrottleLinkage: throttlePosition = 1 - speedControl^gamma
            // speedControl=1 → position=0 → intake.m_throttle=0 → WOT
            simulator_->getEngine()->setSpeedControl(static_cast<double>(t));
        }
    }

    void setIgnition(bool on) {
        if (simulator_ && simulator_->getEngine()) {
            simulator_->getEngine()->getIgnitionModule()->m_enabled = on;
        }
    }

    void setStarterMotor(bool on) {
        if (simulator_) {
            simulator_->m_starterMotor.m_enabled = on;
        }
    }

    double getRPM() const {
        if (simulator_ && simulator_->getEngine()) {
            return simulator_->getEngine()->getRpm();
        }
        return 0.0;
    }

    Simulator* getSimulator() { return simulator_; }
    Engine* getEngine() { return engine_; }
    Vehicle* getVehicle() { return vehicle_; }
    Transmission* getTransmission() { return transmission_; }
    const std::string& getPresetName() const { return presetName_; }
    const std::string& getLastError() const { return lastError_; }

    void cleanup() {
        if (simulator_) {
            simulator_->destroy();
            delete simulator_;
            simulator_ = nullptr;
        }
        // Note: engine_, vehicle_, transmission_ are owned by the simulator
        // after loadSimulation() is called, so do not delete them separately.
        engine_ = nullptr;
        vehicle_ = nullptr;
        transmission_ = nullptr;
    }

private:
    Simulator* simulator_;
    Engine* engine_;
    Vehicle* vehicle_;
    Transmission* transmission_;
    std::string presetName_;
    std::string lastError_;
    int sampleRate_ = TEST_SAMPLE_RATE;
};

// ============================================================================
// GROUP 1: Infrastructure tests (5 tests)
// ============================================================================

class PresetInfrastructureTest : public ::testing::Test {
protected:
    void SetUp() override {}
    void TearDown() override {}
};

TEST_F(PresetInfrastructureTest, LoadFromFileReturnsErrorForMissingFile) {
    PresetLoadResult result = PresetEngineFactory::loadFromFile("/nonexistent/path/fake.json");

    EXPECT_FALSE(result.success())
        << "Factory should report failure for missing file";
    EXPECT_FALSE(result.error.empty())
        << "Error message should describe the failure";
    EXPECT_EQ(result.engine, nullptr)
        << "Engine should be null on failure";
}

TEST_F(PresetInfrastructureTest, LoadFromStringReturnsErrorForInvalidJson) {
    PresetLoadResult result = PresetEngineFactory::loadFromString("not valid json {{{");

    EXPECT_FALSE(result.success())
        << "Factory should report failure for malformed JSON";
    EXPECT_FALSE(result.error.empty())
        << "Error message should describe the parse failure";
}

TEST_F(PresetInfrastructureTest, LoadFromStringReturnsErrorForMissingEngineSection) {
    // Valid JSON but missing required "engine" object
    std::string json = R"({"presetName": "empty", "vehicle": {}})";
    PresetLoadResult result = PresetEngineFactory::loadFromString(json);

    EXPECT_FALSE(result.success())
        << "Factory should fail when engine section is missing";
    EXPECT_FALSE(result.error.empty());
}

TEST_F(PresetInfrastructureTest, HondaPresetLoadsSuccessfully) {
    // Use harness to get proper cleanup via Simulator::destroy()
    PresetSimulatorHarness harness;
    ASSERT_TRUE(harness.initialize(FIXTURE_HONDA))
        << "Failed to load Honda preset: " << harness.getLastError();

    EXPECT_NE(harness.getEngine(), nullptr) << "Engine must not be null";
    EXPECT_NE(harness.getVehicle(), nullptr) << "Vehicle must not be null";
    EXPECT_NE(harness.getTransmission(), nullptr) << "Transmission must not be null";
    EXPECT_FALSE(harness.getPresetName().empty()) << "Preset name must not be empty";

    harness.cleanup();
}

// TDD test: Verify turbulenceToFlameSpeedRatio function is set
// Without this function, combustion fails (flameSpeed() dereferences null pointer)
// causing near-zero RPM and no power output.
TEST_F(PresetInfrastructureTest, PresetEngineHasTurbulenceToFlameSpeedRatioFunction) {
    PresetLoadResult result = PresetEngineFactory::loadFromFile(FIXTURE_HONDA);
    ASSERT_TRUE(result.success())
        << "Failed to load Honda preset: " << result.error;

    ASSERT_NE(result.engine, nullptr) << "Engine must not be null";

    // CRITICAL: turbulenceToFlameSpeedRatio must be set, not null
    // Fuel::flameSpeed() dereferences this pointer without null checking
    // Access protected member via public interface
    // Verify by calling flameSpeed with valid input - it should not crash
    Fuel* fuel = result.engine->getFuel();
    ASSERT_NE(fuel, nullptr) << "Engine must have a Fuel object";

    // Test that flameSpeed doesn't crash when called
    // If turbulenceToFlameSpeedRatio is null, this will crash (which is what we're testing for)
    const double afr = 14.7;
    const double T = units::celcius(25.0);
    const double P = units::pressure(1.0, units::atm);
    const double firingPressure = 1000.0;
    const double motoringPressure = 100.0;

    // This should not crash if turbulence function is properly set
    double flameSpeedValue = fuel->flameSpeed(1.0, afr, T, P, firingPressure, motoringPressure);

    // Assert that we got a reasonable flame speed (not NaN or 0)
    EXPECT_FALSE(std::isnan(flameSpeedValue))
        << "Flame speed should not be NaN - indicates turbulence function is null or invalid";
    EXPECT_GT(flameSpeedValue, 0.1)
        << "Flame speed should be positive - indicates combustion is working";
}

TEST_F(PresetInfrastructureTest, SubaruPresetLoadsSuccessfully) {
    PresetSimulatorHarness harness;
    ASSERT_TRUE(harness.initialize(FIXTURE_SUBARU))
        << "Failed to load Subaru preset: " << harness.getLastError();

    EXPECT_NE(harness.getEngine(), nullptr) << "Engine must not be null";
    EXPECT_NE(harness.getVehicle(), nullptr) << "Vehicle must not be null";
    EXPECT_NE(harness.getTransmission(), nullptr) << "Transmission must not be null";

    harness.cleanup();
}

// ============================================================================
// GROUP 2: PresetSimulatorHarness creates valid simulator (1 per fixture)
// Verifies the full path: JSON -> PresetLoadResult -> PistonEngineSimulator
// ============================================================================

class PresetCreationTest : public ::testing::Test,
                           public ::testing::WithParamInterface<std::string> {
protected:
    void SetUp() override {
        harness_ = std::make_unique<PresetSimulatorHarness>();
    }

    void TearDown() override {
        harness_->cleanup();
        harness_.reset();
    }

    std::unique_ptr<PresetSimulatorHarness> harness_;
};

TEST_P(PresetCreationTest, PresetCreatesValidSimulator) {
    std::string fixturePath = GetParam();

    // Act: Load preset and create simulator
    ASSERT_TRUE(harness_->initialize(fixturePath))
        << "Failed to initialize from " << fixturePath
        << ": " << harness_->getLastError();

    // Assert: Engine must be initialized via the Simulator interface
    Simulator* sim = harness_->getSimulator();
    ASSERT_NE(sim, nullptr);

    Engine* engine = sim->getEngine();
    ASSERT_NE(engine, nullptr)
        << fixturePath << ": Engine is null after loadSimulation";

    // Assert: Vehicle must be initialized
    EXPECT_NE(sim->getVehicle(), nullptr)
        << fixturePath << ": Vehicle is null after loadSimulation";

    // Assert: Transmission must be initialized
    EXPECT_NE(sim->getTransmission(), nullptr)
        << fixturePath << ": Transmission is null after loadSimulation";

    // Assert: Engine name is not empty
    EXPECT_FALSE(engine->getName().empty())
        << fixturePath << ": Engine name is empty";

    // Assert: Engine has cylinders
    EXPECT_GT(engine->getCylinderCount(), 0)
        << fixturePath << ": Engine has zero cylinders";

    // Assert: Engine displacement is reasonable (>0, <20L)
    engine->calculateDisplacement();
    double displacement = engine->getDisplacement();
    EXPECT_GT(displacement, 0.0)
        << fixturePath << ": Engine displacement must be positive";
    EXPECT_LT(displacement, 20.0e-3)
        << fixturePath << ": Engine displacement unreasonably large";
}

INSTANTIATE_TEST_SUITE_P(
    EnginePresets,
    PresetCreationTest,
    ::testing::Values(FIXTURE_HONDA, FIXTURE_SUBARU)
);

// ============================================================================
// GROUP 3: Non-silent audio at idle (1 per fixture)
//
// Critical test: proves the entire JSON -> physics -> audio pipeline works.
// A preset that produces silence is useless.
// ============================================================================

class PresetAudioIdleTest : public ::testing::Test,
                            public ::testing::WithParamInterface<std::string> {
protected:
    void SetUp() override {
        harness_ = std::make_unique<PresetSimulatorHarness>();
    }

    void TearDown() override {
        harness_->cleanup();
        harness_.reset();
    }

    std::unique_ptr<PresetSimulatorHarness> harness_;
};

TEST_P(PresetAudioIdleTest, ProducesNonSilentAudioAtIdle) {
    std::string fixturePath = GetParam();

    // Arrange: Create and initialize preset simulator
    ASSERT_TRUE(harness_->initialize(fixturePath))
        << fixturePath << ": Failed to initialize preset simulator";

    // Enable engine: throttle open + ignition + starter + dyno
    // The dyno provides load so the engine can sustain combustion
    harness_->setThrottle(1.0f);  // Open throttle for cranking
    harness_->setIgnition(true);
    harness_->setStarterMotor(true);
    harness_->getSimulator()->m_dyno.m_enabled = true;
    harness_->getSimulator()->m_dyno.m_hold = true;
    harness_->getSimulator()->m_dyno.m_ks = 10.0;
    harness_->getSimulator()->m_dyno.m_kd = 1.0;
    harness_->getSimulator()->m_dyno.m_rotationSpeed = 2000.0 * (M_PI / 30.0);

    // Act: Run simulation for enough time for engine to start and produce audio
    for (int i = 0; i < 90; ++i) {
        harness_->getSimulator()->startFrame(1.0 / 60.0);
        while (harness_->getSimulator()->simulateStep()) {}
        harness_->getSimulator()->endFrame();
        harness_->getSimulator()->synthesizer().renderAudioOnDemand();
    }
    printf("  [AUDIO-TEST] RPM after cranking: %.2f\n", harness_->getRPM());

    // Disable starter once engine is running on its own power
    harness_->setStarterMotor(false);

    printf("  [AUDIO-TEST] RPM before capture: %.2f\n", harness_->getRPM());
    printf("  [AUDIO-TEST] synthesizer latency: %.0f, inputSampleRate: %.0f\n",
        harness_->getSimulator()->synthesizer().getLatency(),
        harness_->getSimulator()->synthesizer().getInputSampleRate());

    // Drain any audio already in the output buffer
    int16_t drainBuf[100];
    int drained = harness_->getSimulator()->readAudioOutput(100, drainBuf);
    printf("  [AUDIO-TEST] drained %d pre-existing frames, first few: %d %d %d %d %d\n",
        drained, drainBuf[0], drainBuf[1], drainBuf[2], drainBuf[3], drainBuf[4]);

    // Capture audio
    auto audio = harness_->runAndCapture(IDLE_FRAMES);
    ASSERT_FALSE(audio.empty())
        << fixturePath << ": No audio output captured";

    // Assert: Audio must contain signal above noise floor
    EXPECT_TRUE(PresetSimulatorHarness::hasSignal(audio))
        << fixturePath << ": Audio output is silent (all samples below noise floor)";

    // Assert: RMS must be above minimum threshold
    float audioRms = PresetSimulatorHarness::rms(audio);
    EXPECT_GT(audioRms, 0.001f)
        << fixturePath << ": Audio RMS too low (" << audioRms << ")";
}

INSTANTIATE_TEST_SUITE_P(
    EnginePresets,
    PresetAudioIdleTest,
    ::testing::Values(FIXTURE_HONDA, FIXTURE_SUBARU)
);

// ============================================================================
// GROUP 4: Throttle response (1 per fixture)
//
// Verifies that the engine responds to throttle input.
// A non-responding engine is broken or misconfigured.
// ============================================================================

class PresetThrottleTest : public ::testing::Test,
                           public ::testing::WithParamInterface<std::string> {
protected:
    void SetUp() override {
        harness_ = std::make_unique<PresetSimulatorHarness>();
    }

    void TearDown() override {
        harness_->cleanup();
        harness_.reset();
    }

    std::unique_ptr<PresetSimulatorHarness> harness_;
};

TEST_P(PresetThrottleTest, EngineRespondsToThrottleInput) {
    std::string fixturePath = GetParam();

    // Arrange: Create simulator, start engine
    ASSERT_TRUE(harness_->initialize(fixturePath))
        << fixturePath << ": Failed to initialize";

    harness_->setIgnition(true);
    harness_->setStarterMotor(true);
    harness_->setThrottle(1.0f);  // WOT during cranking

    // Crank engine until it starts (2s with starter, no dyno hold).
    // Using starter motor only — no dyno — so the engine learns to
    // sustain itself from the very beginning. The diagnostic test shows
    // both hardcoded and JSON presets reach ~900+ RPM this way.
    for (int i = 0; i < 120; ++i) {
        harness_->getSimulator()->startFrame(1.0 / 60.0);
        while (harness_->getSimulator()->simulateStep()) {}
        harness_->getSimulator()->endFrame();
    }
    double crankingRpm = harness_->getRPM();
    fprintf(stderr, "  [THROTTLE] RPM after cranking: %.2f\n", crankingRpm);
    harness_->setStarterMotor(false);

    // Let engine settle at WOT for 1s
    for (int i = 0; i < 60; ++i) {
        harness_->getSimulator()->startFrame(1.0 / 60.0);
        while (harness_->getSimulator()->simulateStep()) {}
        harness_->getSimulator()->endFrame();
    }
    double wotRpm = harness_->getRPM();

    // Switch to idle throttle for 1s
    harness_->setThrottle(0.0f);
    for (int i = 0; i < 60; ++i) {
        harness_->getSimulator()->startFrame(1.0 / 60.0);
        while (harness_->getSimulator()->simulateStep()) {}
        harness_->getSimulator()->endFrame();
    }
    double idleRpm = harness_->getRPM();

    fprintf(stderr, "  [THROTTLE] WOT=%.2f, Idle=%.2f\n", wotRpm, idleRpm);

    // Assert: WOT RPM must be higher than idle RPM
    EXPECT_GT(wotRpm, idleRpm)
        << fixturePath << ": Engine did not respond to throttle (idle="
        << idleRpm << ", WOT=" << wotRpm << ")";

    // Assert: RPM should be in physically reasonable range
    EXPECT_GT(wotRpm, 500.0)
        << fixturePath << ": WOT RPM unreasonably low (" << wotRpm << ")";
    EXPECT_LT(wotRpm, 12000.0)
        << fixturePath << ": WOT RPM unreasonably high (" << wotRpm << ")";
}

INSTANTIATE_TEST_SUITE_P(
    EnginePresets,
    PresetThrottleTest,
    ::testing::Values(FIXTURE_HONDA, FIXTURE_SUBARU)
);

// ============================================================================
// GROUP 5: Clean shutdown (1 per fixture)
//
// Verifies no crash, no leak, no deadlock on destruction.
// Simulates iOS app being killed while audio is playing.
// ============================================================================

class PresetShutdownTest : public ::testing::Test,
                           public ::testing::WithParamInterface<std::string> {
protected:
    void SetUp() override {}
    void TearDown() override {}
};

TEST_P(PresetShutdownTest, CleanShutdownWhileSimulating) {
    std::string fixturePath = GetParam();

    // Arrange: Create, initialize, start simulating
    PresetSimulatorHarness harness;
    ASSERT_TRUE(harness.initialize(fixturePath));

    // Run some simulation steps
    for (int i = 0; i < 60; ++i) {
        harness.getSimulator()->startFrame(1.0 / 60.0);
        harness.getSimulator()->simulateStep();
        harness.getSimulator()->endFrame();
    }

    // Act: Destroy while simulation is active (no graceful shutdown)
    ASSERT_NO_FATAL_FAILURE(harness.cleanup());

    // Assert: Reaching here without crash is success
    SUCCEED();
}

INSTANTIATE_TEST_SUITE_P(
    EnginePresets,
    PresetShutdownTest,
    ::testing::Values(FIXTURE_HONDA, FIXTURE_SUBARU)
);

// ============================================================================
// GROUP 6: Golden file regression vs Piranha (1 per fixture)
//
// macOS-only. Compares preset factory audio output against the Piranha
// script version. If they match within tolerance, the preset is correct.
//
// iOS builds skip these tests (no Piranha available).
// ============================================================================

#if !TARGET_OS_IPHONE && defined(ENGINE_SIM_PIRANHA_ENABLED)

class PresetGoldenFileTest : public ::testing::Test,
                             public ::testing::WithParamInterface<std::string> {
protected:
    void SetUp() override {}
    void TearDown() override {}

    // Run Piranha script and capture audio output via SimulatorFactory/BridgeSimulator
    std::vector<int16_t> captureFromScript(
        const std::string& scriptPath,
        const std::string& assetBase,
        int frames)
    {
        const std::string absoluteScriptPath = test_path_helpers::makeAbsolutePath(scriptPath);
        const std::string absoluteAssetBase = test_path_helpers::makeAbsolutePath(assetBase);

        ISimulatorConfig config;
        config.sampleRate = TEST_SAMPLE_RATE;
        config.simulationFrequency = 10000;

        std::unique_ptr<ISimulator> isim;
        try {
            test_path_helpers::ScopedWorkingDirectory scopedWorkingDirectory(
                test_path_helpers::engineSimRootForAssets(absoluteAssetBase));
            isim = SimulatorFactory::create(
                SimulatorType::PistonEngine,
                absoluteScriptPath,
                absoluteAssetBase,
                config);
        } catch (const std::exception& e) {
            printf("  [GOLDEN-SCRIPT] Failed to load script '%s': %s\n",
                absoluteScriptPath.c_str(), e.what());
            return {};
        }

        // Get raw Simulator* for direct physics/audio access
        auto* bridge = dynamic_cast<BridgeSimulator*>(isim.get());
        if (!bridge) return {};
        Simulator* sim = bridge->getInternalSimulator();
        if (!sim) return {};

        // Run simulation to let engine start
        if (sim->getEngine()) {
            sim->getEngine()->getIgnitionModule()->m_enabled = true;
            sim->getEngine()->setSpeedControl(1.0);  // WOT during cranking
        }
        sim->m_starterMotor.m_enabled = true;
        for (int i = 0; i < 120; ++i) {
            sim->startFrame(1.0 / 60.0);
            while (sim->simulateStep()) {}
            sim->endFrame();
            sim->synthesizer().renderAudioOnDemand();
        }
        sim->m_starterMotor.m_enabled = false;

        // Let engine settle at WOT
        for (int i = 0; i < 30; ++i) {
            sim->startFrame(1.0 / 60.0);
            while (sim->simulateStep()) {}
            sim->endFrame();
            sim->synthesizer().renderAudioOnDemand();
        }

        // Capture audio
        std::vector<int16_t> audio(frames * STEREO_CHANNELS, 0);
        int totalRead = 0;
        while (totalRead < frames) {
            int toRead = std::min(100, frames - totalRead);
            sim->startFrame(1.0 / 60.0);
            while (sim->simulateStep()) {}
            sim->endFrame();
            sim->synthesizer().renderAudioOnDemand();
            int read = sim->readAudioOutput(
                toRead,
                audio.data() + totalRead * STEREO_CHANNELS);
            if (read > 0) totalRead += read;
            else break;
        }

        audio.resize(totalRead * STEREO_CHANNELS);
        return audio;
    }

    // Run preset factory and capture audio output
    std::vector<int16_t> captureFromPreset(const std::string& fixturePath, int frames) {
        PresetSimulatorHarness harness;
        if (!harness.initialize(fixturePath)) return {};

        harness.setThrottle(1.0f);  // WOT during cranking
        harness.setIgnition(true);
        harness.setStarterMotor(true);
        for (int i = 0; i < 120; ++i) {
            harness.getSimulator()->startFrame(1.0 / 60.0);
            while (harness.getSimulator()->simulateStep()) {}
            harness.getSimulator()->endFrame();
        }
        harness.setStarterMotor(false);

        // Let engine settle at WOT
        for (int i = 0; i < 30; ++i) {
            harness.getSimulator()->startFrame(1.0 / 60.0);
            while (harness.getSimulator()->simulateStep()) {}
            harness.getSimulator()->endFrame();
        }

        return harness.runAndCapture(frames);
    }

    // Calculate RMS difference between two audio buffers
    static float rmsDifference(const std::vector<int16_t>& a,
                               const std::vector<int16_t>& b) {
        if (a.size() != b.size() || a.empty()) return 999.0f;

        double sumSquares = 0.0;
        for (size_t i = 0; i < a.size(); ++i) {
            double diff = (static_cast<double>(a[i]) - static_cast<double>(b[i])) / 32768.0;
            sumSquares += diff * diff;
        }
        return static_cast<float>(std::sqrt(sumSquares / a.size()));
    }
};

TEST_P(PresetGoldenFileTest, PresetAudioMatchesPiranhaScript) {
    const std::string fixturePath = test_path_helpers::makeAbsolutePath(GetParam());

    // Map fixture path to script path (absolute paths via CMake define)
    std::string scriptPath, assetBase;
    assetBase = TEST_ENGINE_SIM_ASSETS "/";
    if (fixturePath.find("honda_trx520") != std::string::npos) {
        scriptPath = TEST_ENGINE_SIM_ASSETS "/engines/atg-video-1/01_honda_trx520.mr";
    } else if (fixturePath.find("subaru_ej25") != std::string::npos) {
        scriptPath = TEST_ENGINE_SIM_ASSETS "/engines/atg-video-2/01_subaru_ej25_eh.mr";
    } else {
        FAIL() << "No script mapping for " << fixturePath;
    }

    scriptPath = test_path_helpers::makeAbsolutePath(scriptPath);
    assetBase = test_path_helpers::makeAbsolutePath(assetBase);

    // Act: Capture audio from both sources
    constexpr int captureFrames = 4800;  // 100ms at 48kHz
    auto scriptAudio = captureFromScript(scriptPath, assetBase, captureFrames);
    auto presetAudio = captureFromPreset(fixturePath, captureFrames);

    ASSERT_FALSE(scriptAudio.empty())
        << "Piranha script produced no audio for " << scriptPath;
    ASSERT_FALSE(presetAudio.empty())
        << "Preset factory produced no audio for " << fixturePath;
    ASSERT_EQ(scriptAudio.size(), presetAudio.size());

    // Assert: Audio outputs must match within RMS tolerance
    // Note: Floating-point nondeterminism prevents bit-exact matching.
    // 1% RMS tolerance accounts for physics simulation variance.
    float rmsDiff = rmsDifference(scriptAudio, presetAudio);
    EXPECT_LT(rmsDiff, 0.01f)
        << fixturePath << ": Preset audio differs from Piranha by "
        << (rmsDiff * 100.0f) << "% RMS";
}

INSTANTIATE_TEST_SUITE_P(
    EnginePresets,
    PresetGoldenFileTest,
    ::testing::Values(FIXTURE_HONDA, FIXTURE_SUBARU)
);

#endif // !TARGET_OS_IPHONE && ENGINE_SIM_PIRANHA_ENABLED

// ============================================================================
// GROUP 7: DestroyWhileAudioThreadRunning stress test
// ============================================================================

TEST_F(PresetInfrastructureTest, DestroyWhileAudioThreadRunning) {
    PresetSimulatorHarness harness;
    ASSERT_TRUE(harness.initialize(FIXTURE_HONDA));

    Simulator* sim = harness.getSimulator();
    sim->startAudioRenderingThread();

    // Give audio thread time to start producing
    std::this_thread::sleep_for(std::chrono::milliseconds(100));

    // Act: Stop audio thread and destroy
    sim->endAudioRenderingThread();
    ASSERT_NO_FATAL_FAILURE(harness.cleanup());

    SUCCEED();
}

// ============================================================================
// GROUP 9: Phase 4 -- SimulatorFactory JSON preset integration
//
// Tests the SimulatorFactory::create() with SimulatorType::PresetEngine.
// Uses the same create() API as SineWave/PistonEngine but passes the preset
// ID as scriptPath parameter. Factory wraps result in BridgeSimulator.
// No Piranha dependency -- pure C++ path.
// ============================================================================

class FactoryPresetTest : public ::testing::Test,
                          public ::testing::WithParamInterface<std::string> {
protected:
    ISimulatorConfig config_;

    void SetUp() override {
        config_.simulationFrequency = EngineSimDefaults::SIMULATION_FREQUENCY;
        config_.fluidSimulationSteps = EngineSimDefaults::FLUID_SIMULATION_STEPS;
        config_.targetSynthesizerLatency = EngineSimDefaults::TARGET_SYNTH_LATENCY;
    }
};

// 9.1: Valid JSON preset path produces non-null ISimulator via factory
TEST_P(FactoryPresetTest, ValidPresetIdReturnsNonNull) {
    auto isim = SimulatorFactory::create(
        SimulatorType::PistonEngine,
        GetParam(),  // JSON file path
        TEST_ES_DIR,
        config_);

    ASSERT_NE(isim, nullptr) << "Factory should return non-null for preset '" << GetParam() << "'";
    isim->destroy();
}

// 9.2: Invalid JSON path throws runtime_error with useful message
TEST_F(PresetInfrastructureTest, FactoryInvalidPresetIdThrowsRuntimeError) {
    ISimulatorConfig config;
    EXPECT_THROW(
        SimulatorFactory::create(
            SimulatorType::PistonEngine,
            "nonexistent_engine_xyz.json",
            "",
            config),
        std::runtime_error);
}

// 9.3: Factory sets a non-empty display name derived from the JSON path
TEST_P(FactoryPresetTest, FactorySetsDisplayNameFromPresetId) {
    auto isim = SimulatorFactory::create(
        SimulatorType::PistonEngine,
        GetParam(),
        TEST_ES_DIR,
        config_);

    ASSERT_NE(isim, nullptr);
    EXPECT_STRNE(isim->getName(), "")
        << "Factory should set a non-empty display name for preset";
    isim->destroy();
}

// 9.4: Factory JSON preset path does NOT depend on ATG_ENGINE_SIM_PIRANHA_ENABLED
// The JSON path in SimulatorFactory::create() has no #ifdef guards — pure C++ + JSON parsing.
// Verified by the existence of tests 9.1-9.3.

// 9.5: Created preset simulator has correct simulation frequency set
TEST_P(FactoryPresetTest, CreatedSimulatorHasSimulationFrequencySet) {
    auto isim = SimulatorFactory::create(
        SimulatorType::PistonEngine,
        GetParam(),
        TEST_ES_DIR,
        config_);

    ASSERT_NE(isim, nullptr);

    auto* bridge = dynamic_cast<BridgeSimulator*>(isim.get());
    ASSERT_NE(bridge, nullptr);
    Simulator* sim = bridge->getInternalSimulator();
    ASSERT_NE(sim, nullptr);

    int freq = sim->getSimulationFrequency();
    EXPECT_GT(freq, 0) << "Simulation frequency must be positive after factory init";
    EXPECT_GE(freq, 1000) << "Simulation frequency unreasonably low";
    EXPECT_LE(freq, 100000) << "Simulation frequency unreasonably high";

    isim->destroy();
}

// 9.6: Factory preset simulator can be stepped without crashing
TEST_P(FactoryPresetTest, FactoryPresetCanBeSteppedViaUpdate) {
    auto isim = SimulatorFactory::create(
        SimulatorType::PistonEngine,
        GetParam(),
        TEST_ES_DIR,
        config_);

    ASSERT_NE(isim, nullptr);

    ASSERT_TRUE(isim->create(config_, nullptr, nullptr));
    isim->update(1.0 / 60.0);
    SUCCEED();
    isim->destroy();
}

INSTANTIATE_TEST_SUITE_P(
    Phase4FactoryPresets,
    FactoryPresetTest,
    ::testing::Values(
        TEST_FIXTURE_DIR "/01_honda_trx520.preset.json",
        TEST_FIXTURE_DIR "/01_subaru_ej25_eh.preset.json",
        TEST_FIXTURE_DIR "/gm_ls.preset.json"
    )
);

// ============================================================================
// GROUP 10: iOS flat bundle path resolution
//
// Simulates the iOS app bundle layout where WAV files are at
// sound-library/new/foo.wav (no es/ directory). The JSON preset stores
// ../../es/sound-library/new/foo.wav, which the deserializer normalizes
// to es/sound-library/new/foo.wav after stripping ../.
//
// The path must resolve deterministically without fallbacks or retries.
// ============================================================================

class IOSFlatBundleTest : public ::testing::Test {
protected:
    std::string tmpDir_;

    void SetUp() override {
        // Create temp directory mimicking iOS app bundle layout:
        //   tmpdir/
        //     preset.json          (copy of real Honda fixture)
        //     sound-library/
        //       new/
        //         mild_exhaust_reverb.wav  (copy of real WAV)
        char tmpl[] = "/tmp/ios_flat_bundle_test_XXXXXX";
        tmpDir_ = mkdtemp(tmpl);

        // Create sound-library/new/ directory
        std::string soundDir = tmpDir_ + "/sound-library/new";
        std::filesystem::create_directories(soundDir);

        // Copy a real WAV file from the test assets
        std::string srcWav = std::string(TEST_ES_DIR) + "/sound-library/new/mild_exhaust_reverb.wav";
        std::string dstWav = soundDir + "/mild_exhaust_reverb.wav";
        ASSERT_TRUE(std::filesystem::copy_file(srcWav, dstWav))
            << "Failed to copy WAV fixture to temp bundle";

        // Copy the real Honda fixture as the preset
        std::string srcJson = std::string(FIXTURE_HONDA);
        std::string dstJson = tmpDir_ + "/preset.json";
        ASSERT_TRUE(std::filesystem::copy_file(srcJson, dstJson))
            << "Failed to copy Honda preset to temp bundle";
    }

    void TearDown() override {
        if (!tmpDir_.empty()) {
            std::filesystem::remove_all(tmpDir_);
        }
    }
};

// Test: The full deterministic path (resolveAssetBasePath result + normalized
// impulse response filename) must point to the actual WAV file on both
// macOS dev layout and iOS flat bundle layout. No fallbacks, no retries.
//
// The JSON stores "../../es/sound-library/new/foo.wav".
// After deserializer normalization, the filename should be "sound-library/new/foo.wav"
// (stripping both "../" prefixes and the "es/" platform-specific prefix).
// resolveAssetBasePath should return the directory that directly contains "sound-library/".
//
// macOS dev: base = <engine-sim-root>/es/, full = <root>/es/sound-library/new/foo.wav
// iOS bundle: base = <bundle>/, full = <bundle>/sound-library/new/foo.wav
TEST_F(IOSFlatBundleTest, ResolvePathFindsWavInFlatBundle) {
    std::string presetPath = tmpDir_ + "/preset.json";

    // Load the preset to get the deserialized exhaust system
    PresetLoadResult result = PresetEngineFactory::loadFromFile(presetPath);
    ASSERT_TRUE(result.success()) << "Failed to load preset: " << result.error;
    ASSERT_NE(result.engine, nullptr);
    ASSERT_GT(result.engine->getExhaustSystemCount(), 0);

    // Get the normalized impulse response filename from the deserialized engine.
    // The JSON stores "../../es/sound-library/new/mild_exhaust_reverb.wav".
    // After the fix, the deserializer should strip ../ AND es/ to produce
    // "sound-library/new/mild_exhaust_reverb.wav".
    ExhaustSystem* exhaust = result.engine->getExhaustSystem(0);
    ASSERT_NE(exhaust, nullptr);
    ImpulseResponse* ir = exhaust->getImpulseResponse();
    ASSERT_NE(ir, nullptr);
    std::string irFilename = ir->getFilename();

    // Resolve the asset base path (simulating iOS flat bundle)
    std::string normalizedPath = ScriptLoadHelpers::normalizeScriptPath(presetPath);
    std::string basePath = ScriptLoadHelpers::resolveAssetBasePath(normalizedPath, "");

    // The combined path must resolve to an existing WAV file
    // On iOS flat bundle: base = <bundle>/, filename = sound-library/new/foo.wav
    // On macOS dev: base = <root>/es/, filename = sound-library/new/foo.wav
    std::string fullPath = basePath + "/" + irFilename;
    bool exists = std::filesystem::exists(fullPath);

    EXPECT_TRUE(exists)
        << "Flat bundle path resolution failed.\n"
        << "  basePath: " << basePath << "\n"
        << "  irFilename: " << irFilename << "\n"
        << "  fullPath: " << fullPath << "\n"
        << "  Expected WAV at: " << tmpDir_ << "/sound-library/new/mild_exhaust_reverb.wav\n"
        << "  (iOS flat bundle has no es/ directory)";
}

// Test: loadImpulseResponses works deterministically with the flat bundle
// No fallbacks or retries -- the path must resolve on the first attempt.
TEST_F(IOSFlatBundleTest, LoadImpulseResponsesWorksWithFlatBundle) {
    std::string presetPath = tmpDir_ + "/preset.json";

    // Load preset from the flat bundle (uses real Honda fixture JSON)
    PresetLoadResult result = PresetEngineFactory::loadFromFile(presetPath);
    ASSERT_TRUE(result.success()) << "Failed to load preset: " << result.error;
    ASSERT_NE(result.engine, nullptr);

    // Create simulator and load engine
    auto* pistonSim = new PistonEngineSimulator();
    Simulator::Parameters params;
    params.systemType = Simulator::SystemType::NsvOptimized;
    pistonSim->initialize(params);
    pistonSim->loadSimulation(result.engine, result.vehicle, result.transmission);

    // Resolve the asset base path from the preset location (simulating iOS)
    std::string normalizedPath = ScriptLoadHelpers::normalizeScriptPath(presetPath);
    std::string basePath = ScriptLoadHelpers::resolveAssetBasePath(normalizedPath, "");

    // Load impulse responses -- must succeed on first attempt, no fallbacks
    bool loaded = ScriptLoadHelpers::loadImpulseResponses(
        pistonSim, result.engine, basePath, nullptr);

    EXPECT_TRUE(loaded)
        << "loadImpulseResponses failed on iOS flat bundle layout.\n"
        << "  basePath: " << basePath << "\n"
        << "  The path must resolve deterministically without fallbacks.";

    pistonSim->destroy();
    delete pistonSim;
}
