// PresetEngineTests.cpp - GREEN-phase tests for JSON engine presets
//
// Purpose: Verify that JSON preset deserialization produces correct engine
// simulations that can be loaded into a PistonEngineSimulator for audio
// production. Tests the full path: JSON -> PresetLoadResult -> Simulator.
//
// Architecture:
//   PresetEngineFactory::loadFromFile(path) returns PresetLoadResult
//   containing raw Engine*/Vehicle*/Transmission* pointers.
//   Caller creates a PistonEngineSimulator and calls loadSimulation().
//
// Test count: 15 (7 infrastructure + 4 per-engine * 2 engines)
//
// Data dependency: Tests need JSON preset files in test/fixtures/
// Generated by: engine-sim-preset-compiler <script.mr> <output.json>
//
// Build: cmake -DBUILD_PRESET_ENGINE_TESTS=ON
//   macOS: 15 tests (golden file tests use Piranha as reference)
//   iOS: 15 tests (golden file tests skipped -- no Piranha on iOS)

#include <gtest/gtest.h>
#include <memory>
#include <vector>
#include <cmath>
#include <cstring>
#include <chrono>
#include <algorithm>
#include <fstream>

// Engine-sim headers
#include "simulator.h"
#include "piston_engine_simulator.h"
#include "engine.h"
#include "vehicle.h"
#include "transmission.h"
#include "synthesizer.h"
#include "starter_motor.h"

// Bridge headers
#include "simulator/engine_sim_bridge.h"
#include "simulator/PresetEngineFactory.h"
#include "common/ILogging.h"

// ============================================================================
// Constants
// ============================================================================

namespace {
    constexpr int TEST_SAMPLE_RATE = 48000;
    constexpr int STEREO_CHANNELS = 2;
    constexpr int IDLE_FRAMES = 4800;          // 100ms at 48kHz

    // Noise floor threshold for "non-silent" detection
    constexpr float NOISE_FLOOR = 100.0f;  // int16_t scale

    // Fixture paths - TEST_FIXTURE_DIR is set by CMake to the absolute
    // path of engine-sim-bridge/test/fixtures/
    const std::string FIXTURE_HONDA = TEST_FIXTURE_DIR "/01_honda_trx520.preset.json";
    const std::string FIXTURE_SUBARU = TEST_FIXTURE_DIR "/01_subaru_ej25_eh.preset.json";
}

// ============================================================================
// Test Harness - Preset simulator lifecycle and audio capture
//
// Creates a PistonEngineSimulator, loads a JSON preset via
// PresetEngineFactory::loadFromFile(), then calls loadSimulation().
// Follows the same pattern as EngineSimLoadPreset() in engine_sim_bridge.cpp.
// ============================================================================

class PresetSimulatorHarness {
public:
    PresetSimulatorHarness()
        : simulator_(nullptr)
        , engine_(nullptr)
        , vehicle_(nullptr)
        , transmission_(nullptr)
    {}

    ~PresetSimulatorHarness() {
        cleanup();
    }

    // Load a JSON preset file and wire it into a PistonEngineSimulator.
    // Returns true on success.
    bool initialize(const std::string& fixturePath) {
        // Step 1: Load preset from JSON
        PresetLoadResult result = PresetEngineFactory::loadFromFile(fixturePath);
        if (!result.success()) {
            lastError_ = result.error;
            return false;
        }

        engine_ = result.engine;
        vehicle_ = result.vehicle;
        transmission_ = result.transmission;
        presetName_ = result.presetName;

        // Step 2: Create and initialize PistonEngineSimulator
        auto* pistonSim = new PistonEngineSimulator();
        pistonSim->setFluidSimulationSteps(8);

        Simulator::Parameters params;
        params.systemType = Simulator::SystemType::NsvOptimized;
        pistonSim->initialize(params);
        pistonSim->setSimulationFrequency(10000);
        pistonSim->setTargetSynthesizerLatency(0.05);

        simulator_ = pistonSim;

        // Step 3: Load the engine into the simulator
        simulator_->loadSimulation(engine_, vehicle_, transmission_);

        return true;
    }

    // Run simulation and capture audio output (on-demand rendering)
    std::vector<int16_t> runAndCapture(int framesToGenerate) {
        if (!simulator_) return {};

        std::vector<int16_t> audioOutput(framesToGenerate * STEREO_CHANNELS, 0);

        const int framesPerStep = 100;
        int framesGenerated = 0;

        while (framesGenerated < framesToGenerate) {
            int framesToRead = std::min(framesPerStep, framesToGenerate - framesGenerated);

            simulator_->startFrame(1.0 / 60.0);
            simulator_->simulateStep();
            simulator_->endFrame();

            int framesRead = simulator_->readAudioOutput(
                framesToRead,
                audioOutput.data() + framesGenerated * STEREO_CHANNELS
            );

            if (framesRead <= 0) {
                simulator_->synthesizer().renderAudioOnDemand();
                framesRead = simulator_->readAudioOutput(
                    framesToRead,
                    audioOutput.data() + framesGenerated * STEREO_CHANNELS
                );
            }

            if (framesRead <= 0) break;

            framesGenerated += framesRead;
        }

        return audioOutput;
    }

    // Calculate RMS of audio samples
    static float rms(const std::vector<int16_t>& samples) {
        if (samples.empty()) return 0.0f;
        double sumSquares = 0.0;
        for (int16_t s : samples) {
            double f = static_cast<double>(s) / 32768.0;
            sumSquares += f * f;
        }
        return static_cast<float>(std::sqrt(sumSquares / samples.size()));
    }

    // Check if audio contains signal above noise floor
    static bool hasSignal(const std::vector<int16_t>& samples, int16_t threshold = 100) {
        for (int16_t s : samples) {
            if (std::abs(s) > threshold) return true;
        }
        return false;
    }

    // Engine controls
    void setThrottle(float t) {
        if (simulator_ && simulator_->getEngine()) {
            simulator_->getEngine()->setThrottle(static_cast<double>(t));
        }
    }

    void setIgnition(bool on) {
        if (simulator_ && simulator_->getEngine()) {
            simulator_->getEngine()->setSpeedControl(on ? 1.0 : 0.0);
        }
    }

    void setStarterMotor(bool on) {
        if (simulator_) {
            simulator_->m_starterMotor.m_enabled = on;
        }
    }

    double getRPM() const {
        if (simulator_ && simulator_->getEngine()) {
            return simulator_->getEngine()->getRpm();
        }
        return 0.0;
    }

    Simulator* getSimulator() { return simulator_; }
    Engine* getEngine() { return engine_; }
    Vehicle* getVehicle() { return vehicle_; }
    Transmission* getTransmission() { return transmission_; }
    const std::string& getPresetName() const { return presetName_; }
    const std::string& getLastError() const { return lastError_; }

    void cleanup() {
        if (simulator_) {
            simulator_->destroy();
            delete simulator_;
            simulator_ = nullptr;
        }
        // Note: engine_, vehicle_, transmission_ are owned by the simulator
        // after loadSimulation() is called, so do not delete them separately.
        engine_ = nullptr;
        vehicle_ = nullptr;
        transmission_ = nullptr;
    }

private:
    Simulator* simulator_;
    Engine* engine_;
    Vehicle* vehicle_;
    Transmission* transmission_;
    std::string presetName_;
    std::string lastError_;
    int sampleRate_ = TEST_SAMPLE_RATE;
};

// ============================================================================
// GROUP 1: Infrastructure tests (5 tests)
// ============================================================================

class PresetInfrastructureTest : public ::testing::Test {
protected:
    void SetUp() override {}
    void TearDown() override {}
};

TEST_F(PresetInfrastructureTest, LoadFromFileReturnsErrorForMissingFile) {
    PresetLoadResult result = PresetEngineFactory::loadFromFile("/nonexistent/path/fake.json");

    EXPECT_FALSE(result.success())
        << "Factory should report failure for missing file";
    EXPECT_FALSE(result.error.empty())
        << "Error message should describe the failure";
    EXPECT_EQ(result.engine, nullptr)
        << "Engine should be null on failure";
}

TEST_F(PresetInfrastructureTest, LoadFromStringReturnsErrorForInvalidJson) {
    PresetLoadResult result = PresetEngineFactory::loadFromString("not valid json {{{");

    EXPECT_FALSE(result.success())
        << "Factory should report failure for malformed JSON";
    EXPECT_FALSE(result.error.empty())
        << "Error message should describe the parse failure";
}

TEST_F(PresetInfrastructureTest, LoadFromStringReturnsErrorForMissingEngineSection) {
    // Valid JSON but missing required "engine" object
    std::string json = R"({"presetName": "empty", "vehicle": {}})";
    PresetLoadResult result = PresetEngineFactory::loadFromString(json);

    EXPECT_FALSE(result.success())
        << "Factory should fail when engine section is missing";
    EXPECT_FALSE(result.error.empty());
}

TEST_F(PresetInfrastructureTest, HondaPresetLoadsSuccessfully) {
    // Use harness to get proper cleanup via Simulator::destroy()
    PresetSimulatorHarness harness;
    ASSERT_TRUE(harness.initialize(FIXTURE_HONDA))
        << "Failed to load Honda preset: " << harness.getLastError();

    EXPECT_NE(harness.getEngine(), nullptr) << "Engine must not be null";
    EXPECT_NE(harness.getVehicle(), nullptr) << "Vehicle must not be null";
    EXPECT_NE(harness.getTransmission(), nullptr) << "Transmission must not be null";
    EXPECT_FALSE(harness.getPresetName().empty()) << "Preset name must not be empty";

    harness.cleanup();
}

TEST_F(PresetInfrastructureTest, SubaruPresetLoadsSuccessfully) {
    PresetSimulatorHarness harness;
    ASSERT_TRUE(harness.initialize(FIXTURE_SUBARU))
        << "Failed to load Subaru preset: " << harness.getLastError();

    EXPECT_NE(harness.getEngine(), nullptr) << "Engine must not be null";
    EXPECT_NE(harness.getVehicle(), nullptr) << "Vehicle must not be null";
    EXPECT_NE(harness.getTransmission(), nullptr) << "Transmission must not be null";

    harness.cleanup();
}

// ============================================================================
// GROUP 2: PresetSimulatorHarness creates valid simulator (1 per fixture)
// Verifies the full path: JSON -> PresetLoadResult -> PistonEngineSimulator
// ============================================================================

class PresetCreationTest : public ::testing::Test,
                           public ::testing::WithParamInterface<std::string> {
protected:
    void SetUp() override {
        harness_ = std::make_unique<PresetSimulatorHarness>();
    }

    void TearDown() override {
        harness_->cleanup();
        harness_.reset();
    }

    std::unique_ptr<PresetSimulatorHarness> harness_;
};

TEST_P(PresetCreationTest, PresetCreatesValidSimulator) {
    std::string fixturePath = GetParam();

    // Act: Load preset and create simulator
    ASSERT_TRUE(harness_->initialize(fixturePath))
        << "Failed to initialize from " << fixturePath
        << ": " << harness_->getLastError();

    // Assert: Engine must be initialized via the Simulator interface
    Simulator* sim = harness_->getSimulator();
    ASSERT_NE(sim, nullptr);

    Engine* engine = sim->getEngine();
    ASSERT_NE(engine, nullptr)
        << fixturePath << ": Engine is null after loadSimulation";

    // Assert: Vehicle must be initialized
    EXPECT_NE(sim->getVehicle(), nullptr)
        << fixturePath << ": Vehicle is null after loadSimulation";

    // Assert: Transmission must be initialized
    EXPECT_NE(sim->getTransmission(), nullptr)
        << fixturePath << ": Transmission is null after loadSimulation";

    // Assert: Engine name is not empty
    EXPECT_FALSE(engine->getName().empty())
        << fixturePath << ": Engine name is empty";

    // Assert: Engine has cylinders
    EXPECT_GT(engine->getCylinderCount(), 0)
        << fixturePath << ": Engine has zero cylinders";

    // Assert: Engine displacement is reasonable (>0, <20L)
    engine->calculateDisplacement();
    double displacement = engine->getDisplacement();
    EXPECT_GT(displacement, 0.0)
        << fixturePath << ": Engine displacement must be positive";
    EXPECT_LT(displacement, 20.0e-3)
        << fixturePath << ": Engine displacement unreasonably large";
}

INSTANTIATE_TEST_SUITE_P(
    EnginePresets,
    PresetCreationTest,
    ::testing::Values(FIXTURE_HONDA, FIXTURE_SUBARU)
);

// ============================================================================
// GROUP 3: Non-silent audio at idle (1 per fixture)
//
// Critical test: proves the entire JSON -> physics -> audio pipeline works.
// A preset that produces silence is useless.
// ============================================================================

class PresetAudioIdleTest : public ::testing::Test,
                            public ::testing::WithParamInterface<std::string> {
protected:
    void SetUp() override {
        harness_ = std::make_unique<PresetSimulatorHarness>();
    }

    void TearDown() override {
        harness_->cleanup();
        harness_.reset();
    }

    std::unique_ptr<PresetSimulatorHarness> harness_;
};

TEST_P(PresetAudioIdleTest, ProducesNonSilentAudioAtIdle) {
    std::string fixturePath = GetParam();

    // Arrange: Create and initialize preset simulator
    ASSERT_TRUE(harness_->initialize(fixturePath))
        << fixturePath << ": Failed to initialize preset simulator";

    // Enable engine: ignition + starter
    harness_->setIgnition(true);
    harness_->setStarterMotor(true);

    // Act: Run simulation for enough time for engine to "start" and produce audio
    for (int i = 0; i < 30; ++i) {
        harness_->getSimulator()->startFrame(1.0 / 60.0);
        harness_->getSimulator()->simulateStep();
        harness_->getSimulator()->endFrame();
    }

    // Disable starter once engine is "running"
    harness_->setStarterMotor(false);

    // Capture audio
    auto audio = harness_->runAndCapture(IDLE_FRAMES);
    ASSERT_FALSE(audio.empty())
        << fixturePath << ": No audio output captured";

    // Assert: Audio must contain signal above noise floor
    EXPECT_TRUE(PresetSimulatorHarness::hasSignal(audio))
        << fixturePath << ": Audio output is silent (all samples below noise floor)";

    // Assert: RMS must be above minimum threshold
    float audioRms = PresetSimulatorHarness::rms(audio);
    EXPECT_GT(audioRms, 0.001f)
        << fixturePath << ": Audio RMS too low (" << audioRms << ")";
}

INSTANTIATE_TEST_SUITE_P(
    EnginePresets,
    PresetAudioIdleTest,
    ::testing::Values(FIXTURE_HONDA, FIXTURE_SUBARU)
);

// ============================================================================
// GROUP 4: Throttle response (1 per fixture)
//
// Verifies that the engine responds to throttle input.
// A non-responding engine is broken or misconfigured.
// ============================================================================

class PresetThrottleTest : public ::testing::Test,
                           public ::testing::WithParamInterface<std::string> {
protected:
    void SetUp() override {
        harness_ = std::make_unique<PresetSimulatorHarness>();
    }

    void TearDown() override {
        harness_->cleanup();
        harness_.reset();
    }

    std::unique_ptr<PresetSimulatorHarness> harness_;
};

TEST_P(PresetThrottleTest, EngineRespondsToThrottleInput) {
    std::string fixturePath = GetParam();

    // Arrange: Create simulator, start engine
    ASSERT_TRUE(harness_->initialize(fixturePath))
        << fixturePath << ": Failed to initialize";

    harness_->setIgnition(true);
    harness_->setStarterMotor(true);

    // Run engine until started
    for (int i = 0; i < 30; ++i) {
        harness_->getSimulator()->startFrame(1.0 / 60.0);
        harness_->getSimulator()->simulateStep();
        harness_->getSimulator()->endFrame();
    }
    harness_->setStarterMotor(false);

    // Act: Set throttle to idle and measure RPM
    harness_->setThrottle(0.0f);
    for (int i = 0; i < 30; ++i) {
        harness_->getSimulator()->startFrame(1.0 / 60.0);
        harness_->getSimulator()->simulateStep();
        harness_->getSimulator()->endFrame();
    }
    double idleRpm = harness_->getRPM();

    // Act: Set throttle to wide-open and measure RPM
    harness_->setThrottle(1.0f);
    for (int i = 0; i < 60; ++i) {
        harness_->getSimulator()->startFrame(1.0 / 60.0);
        harness_->getSimulator()->simulateStep();
        harness_->getSimulator()->endFrame();
    }
    double wotRpm = harness_->getRPM();

    // Assert: WOT RPM must be higher than idle RPM
    EXPECT_GT(wotRpm, idleRpm)
        << fixturePath << ": Engine did not respond to throttle (idle="
        << idleRpm << ", WOT=" << wotRpm << ")";

    // Assert: RPM should be in physically reasonable range
    EXPECT_GT(wotRpm, 500.0)
        << fixturePath << ": WOT RPM unreasonably low (" << wotRpm << ")";
    EXPECT_LT(wotRpm, 12000.0)
        << fixturePath << ": WOT RPM unreasonably high (" << wotRpm << ")";
}

INSTANTIATE_TEST_SUITE_P(
    EnginePresets,
    PresetThrottleTest,
    ::testing::Values(FIXTURE_HONDA, FIXTURE_SUBARU)
);

// ============================================================================
// GROUP 5: Clean shutdown (1 per fixture)
//
// Verifies no crash, no leak, no deadlock on destruction.
// Simulates iOS app being killed while audio is playing.
// ============================================================================

class PresetShutdownTest : public ::testing::Test,
                           public ::testing::WithParamInterface<std::string> {
protected:
    void SetUp() override {}
    void TearDown() override {}
};

TEST_P(PresetShutdownTest, CleanShutdownWhileSimulating) {
    std::string fixturePath = GetParam();

    // Arrange: Create, initialize, start simulating
    PresetSimulatorHarness harness;
    ASSERT_TRUE(harness.initialize(fixturePath));

    // Run some simulation steps
    for (int i = 0; i < 60; ++i) {
        harness.getSimulator()->startFrame(1.0 / 60.0);
        harness.getSimulator()->simulateStep();
        harness.getSimulator()->endFrame();
    }

    // Act: Destroy while simulation is active (no graceful shutdown)
    ASSERT_NO_FATAL_FAILURE(harness.cleanup());

    // Assert: Reaching here without crash is success
    SUCCEED();
}

INSTANTIATE_TEST_SUITE_P(
    EnginePresets,
    PresetShutdownTest,
    ::testing::Values(FIXTURE_HONDA, FIXTURE_SUBARU)
);

// ============================================================================
// GROUP 6: Golden file regression vs Piranha (1 per fixture)
//
// macOS-only. Compares preset factory audio output against the Piranha
// script version. If they match within tolerance, the preset is correct.
//
// iOS builds skip these tests (no Piranha available).
// ============================================================================

#if !TARGET_OS_IPHONE && defined(ENGINE_SIM_PIRANHA_ENABLED)

class PresetGoldenFileTest : public ::testing::Test,
                             public ::testing::WithParamInterface<std::string> {
protected:
    void SetUp() override {}
    void TearDown() override {}

    // Run Piranha script and capture audio output
    std::vector<int16_t> captureFromScript(
        const std::string& scriptPath,
        const std::string& assetBase,
        int frames)
    {
        EngineSimAPI api;
        EngineSimHandle handle = nullptr;
        EngineSimConfig config = {};
        config.sampleRate = TEST_SAMPLE_RATE;
        config.sineMode = 0;
        config.simulationFrequency = 10000;

        EngineSimResult r = api.Create(&config, &handle);
        if (r != ESIM_SUCCESS) return {};

        r = api.LoadScript(handle, scriptPath.c_str(), assetBase.c_str());
        if (r != ESIM_SUCCESS) {
            api.Destroy(handle);
            return {};
        }

        // Run simulation to let engine start
        api.SetIgnition(handle, 1);
        api.SetStarterMotor(handle, 1);
        for (int i = 0; i < 60; ++i) {
            api.Update(handle, 1.0 / 60.0);
        }
        api.SetStarterMotor(handle, 0);

        // Capture audio
        std::vector<int16_t> audio(frames * STEREO_CHANNELS, 0);
        int32_t totalRead = 0;
        while (totalRead < frames) {
            int32_t toRead = std::min(100, frames - totalRead);
            int32_t read = 0;
            api.ReadAudioBuffer(handle,
                audio.data() + totalRead * STEREO_CHANNELS,
                toRead, &read);
            api.Update(handle, 1.0 / 60.0);
            if (read > 0) totalRead += read;
            else break;
        }

        api.Destroy(handle);
        return audio;
    }

    // Run preset factory and capture audio output
    std::vector<int16_t> captureFromPreset(const std::string& fixturePath, int frames) {
        PresetSimulatorHarness harness;
        if (!harness.initialize(fixturePath)) return {};

        harness.setIgnition(true);
        harness.setStarterMotor(true);
        for (int i = 0; i < 60; ++i) {
            harness.getSimulator()->startFrame(1.0 / 60.0);
            harness.getSimulator()->simulateStep();
            harness.getSimulator()->endFrame();
        }
        harness.setStarterMotor(false);

        return harness.runAndCapture(frames);
    }

    // Calculate RMS difference between two audio buffers
    static float rmsDifference(const std::vector<int16_t>& a,
                               const std::vector<int16_t>& b) {
        if (a.size() != b.size() || a.empty()) return 999.0f;

        double sumSquares = 0.0;
        for (size_t i = 0; i < a.size(); ++i) {
            double diff = (static_cast<double>(a[i]) - static_cast<double>(b[i])) / 32768.0;
            sumSquares += diff * diff;
        }
        return static_cast<float>(std::sqrt(sumSquares / a.size()));
    }
};

TEST_P(PresetGoldenFileTest, PresetAudioMatchesPiranhaScript) {
    std::string fixturePath = GetParam();

    // Map fixture path to script path
    std::string scriptPath, assetBase;
    if (fixturePath.find("honda_trx520") != std::string::npos) {
        scriptPath = "engines/atg-video-1/01_honda_trx520.mr";
        assetBase = "assets/";
    } else if (fixturePath.find("subaru_ej25") != std::string::npos) {
        scriptPath = "engines/atg-video-2/01_subaru_ej25_eh.mr";
        assetBase = "assets/";
    } else {
        GTEST_SKIP() << "No script mapping for " << fixturePath;
    }

    // Act: Capture audio from both sources
    constexpr int captureFrames = 4800;  // 100ms at 48kHz
    auto scriptAudio = captureFromScript(scriptPath, assetBase, captureFrames);
    auto presetAudio = captureFromPreset(fixturePath, captureFrames);

    ASSERT_FALSE(scriptAudio.empty()) << "Piranha script produced no audio";
    ASSERT_FALSE(presetAudio.empty()) << "Preset factory produced no audio";
    ASSERT_EQ(scriptAudio.size(), presetAudio.size());

    // Assert: Audio outputs must match within RMS tolerance
    // Note: Floating-point nondeterminism prevents bit-exact matching.
    // 1% RMS tolerance accounts for physics simulation variance.
    float rmsDiff = rmsDifference(scriptAudio, presetAudio);
    EXPECT_LT(rmsDiff, 0.01f)
        << fixturePath << ": Preset audio differs from Piranha by "
        << (rmsDiff * 100.0f) << "% RMS";
}

INSTANTIATE_TEST_SUITE_P(
    EnginePresets,
    PresetGoldenFileTest,
    ::testing::Values(FIXTURE_HONDA, FIXTURE_SUBARU)
);

#endif // !TARGET_OS_IPHONE && ENGINE_SIM_PIRANHA_ENABLED

// ============================================================================
// GROUP 7: DestroyWhileAudioThreadRunning stress test
// ============================================================================

TEST_F(PresetInfrastructureTest, DestroyWhileAudioThreadRunning) {
    PresetSimulatorHarness harness;
    ASSERT_TRUE(harness.initialize(FIXTURE_HONDA));

    Simulator* sim = harness.getSimulator();
    sim->startAudioRenderingThread();

    // Give audio thread time to start producing
    std::this_thread::sleep_for(std::chrono::milliseconds(100));

    // Act: Stop audio thread and destroy
    sim->endAudioRenderingThread();
    ASSERT_NO_FATAL_FAILURE(harness.cleanup());

    SUCCEED();
}
