// PresetEngineFactory.h - Constructs Engine/Vehicle/Transmission from JSON presets
// iOS runtime: reads JSON presets generated by the macOS preset compiler
// No Piranha/Boost dependency -- works on all platforms
//
// SRP: Single responsibility - deserialize JSON presets into engine objects
// OCP: New engine types supported via JSON, no code changes needed
// DIP: Depends on Engine/vehicle/transmission abstractions, not Piranha

#ifndef PRESET_ENGINE_FACTORY_H
#define PRESET_ENGINE_FACTORY_H

#include <string>
#include <cstdint>

#include "common/JsonParser.h"

// Forward declarations
class Engine;
class Vehicle;
class Transmission;

struct EngineSimContext;

// Result of preset loading
struct PresetLoadResult {
    Engine* engine;
    Vehicle* vehicle;
    Transmission* transmission;
    std::string presetName;
    std::string error;

    PresetLoadResult() : engine(nullptr), vehicle(nullptr), transmission(nullptr) {}
    bool success() const { return engine != nullptr && error.empty(); }
};

// PresetEngineFactory - Reads JSON presets and constructs engine object graphs
//
// Two loading modes:
// 1. loadFromFile() - reads JSON from a file path (macOS/desktop)
// 2. loadFromJson() - reads JSON from an in-memory string (iOS/embedded)
//
// Usage:
//   PresetLoadResult result = PresetEngineFactory::loadFromJson(jsonStr, jsonLen);
//   if (result.success()) {
//       simulator->loadSimulation(result.engine, result.vehicle, result.transmission);
//   }
class PresetEngineFactory {
public:
    // Load preset from JSON file (desktop path)
    static PresetLoadResult loadFromFile(const std::string& jsonPath);

    // Load preset from JSON string (for embedded presets or in-memory data)
    static PresetLoadResult loadFromString(const std::string& jsonContent, const std::string& sourceName = "<string>");

    // Load preset from raw JSON bytes (C API friendly, for iOS bridge)
    static PresetLoadResult loadFromJson(const char* jsonContent, size_t jsonSize);

private:
    // Construction helpers (internal, maps JSON values to engine-sim Parameters)
    static void configureEngine(json::JsonValue& engineJson, Engine* engine);
    static void configureCrankshafts(json::JsonValue& crankshaftsJson, Engine* engine);
    static void configureCylinderBanks(json::JsonValue& banksJson, Engine* engine);
    static void configureExhaustSystems(json::JsonValue& exhaustsJson, Engine* engine);
    static void configureIntakes(json::JsonValue& intakesJson, Engine* engine);
    static void configureFuel(json::JsonValue& fuelJson, Engine* engine);
    static void configureIgnition(json::JsonValue& engineJson, Engine* engine);

    static Vehicle* constructVehicle(json::JsonValue& vehicleJson);
    static Transmission* constructTransmission(json::JsonValue& transJson);
};

#endif // PRESET_ENGINE_FACTORY_H
